version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - ./catalogue-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: catalogue

volumes:
  catalogue-data:
