spring:
  security:
    user:
      name: catalogue_service_user
      password: '{noop}password'
      roles:
        - SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5433/catalogue
    username: admin
    password: admin
  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    show-sql: true
server:
  port: 8081
logging:
  level:
    sql: info
